name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true  # Export creds for docker auth

      - name: Authenticate Docker with Google Cloud
        run: |
          gcloud auth configure-docker

      - name: Build and Push Docker image to GCR
        run: |
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT }}/api
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy api \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/api \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
